"""Generate C++ GDExtension data classes for Box3D structs.

For each struct marked as 'data_class' in type_map.yaml, generates a RefCounted
subclass with typed properties, to_b3()/from_b3() conversion methods, and
ClassDB registration via _bind_methods().
"""

import shutil
from pathlib import Path

from parser import (
    Struct,
    StructField,
    parse_headers,
)
from type_conversions import (
    convert_to_b3,
    convert_to_godot,
    to_godot_type,
)
from classification import blob_structs, infer_clone_fn, infer_destroy_fn
from utils import (
    FieldClassification,
    build_enum_info,
    classify_field,
    collect_convertible_fields,
    compute_struct_dependencies,
    data_class_filename,
    load_type_map,
    to_godot_class_name,
    to_snake_case,
    topological_sort,
    _resolve_field_type,
)


def generate_helper_functions() -> str:
    """Generate shared helper functions for data class conversions."""
    return """\
// Helper: create a Ref<T> from a b3 struct using from_b3()
template <typename B3T, typename GodotClass>
static Ref<GodotClass> _from_b3_to_ref(const B3T& p_b3) {
    Ref<GodotClass> ref;
    ref.instantiate();
    ref->from_b3(p_b3);
    return ref;
}

// Helper: extract b3 struct from a Ref<T> using to_b3()
template <typename B3T, typename GodotClass>
static B3T _ref_to_b3(const Ref<GodotClass>& p_ref) {
    B3T result;
    if (p_ref.is_valid()) {
        result = p_ref->to_b3();
    }
    return result;
}

// Helper: get raw b3 struct pointer from a Ref<T> using ptr()
template <typename B3T, typename GodotClass>
static const B3T* _ref_ptr(const Ref<GodotClass>& p_ref) {
    return p_ref.is_valid() ? p_ref->ptr() : nullptr;
}

// Helper: build PackedFloat32Array or PackedInt32Array from C array
template <typename PackedArr, typename ElemType, size_t N>
static PackedArr _make_packed_array(const ElemType (&p_src)[N], PackedArr p_dst, size_t p_size) {
    p_dst.resize(p_size);
    for (size_t i = 0; i < p_size; i++) {
        p_dst.set(i, p_src[i]);
    }
    return p_dst;
}

// Helper: unpack Packed*Array into C array
template <typename PackedArr, typename ElemType, size_t N>
static void _unpack_array(const PackedArr& p_src, ElemType (&p_dst)[N], size_t p_size) {
    for (size_t i = 0; i < p_size && i < (size_t)p_src.size(); i++) {
        p_dst[i] = p_src[i];
    }
}
"""


def _is_child_struct(struct: Struct, type_map: dict, all_struct_names: set,
                     skip_structs: set) -> bool:
    """Check if this struct is used as a NESTED_STRUCT field in any other struct."""
    # A struct is a "child" if it could be classified as NESTED_STRUCT.
    # This means it's in all_struct_names, not skipped, not an enum, not a math/id type.
    if struct.name in skip_structs:
        return False
    if struct.name in type_map.get("enums", []):
        return False
    if struct.name in type_map.get("math_types", {}):
        return False
    if struct.name in type_map.get("id_types", {}):
        return False
    return True


def generate_header(struct: Struct, type_map: dict, all_struct_names: set,
                    skip_structs: set) -> tuple[str, list[str]]:
    """Generate header file for a data class.

    Returns (header_content, warnings).
    """
    cls_name = to_godot_class_name(struct.name)
    warnings = []
    convertible_fields = []

    for field in struct.fields:
        cls = classify_field(field, type_map, all_struct_names, skip_structs)
        if cls not in (FieldClassification.POINTER, FieldClassification.SKIP_ARRAY, FieldClassification.UNKNOWN):
            convertible_fields.append((field, cls))
        else:
            warnings.append(f"  {struct.name}.{field.name}: skipping ({field.type})")

    if not convertible_fields:
        return "", warnings

    is_child = _is_child_struct(struct, type_map, all_struct_names, skip_structs)

    lines = [
        "#pragma once",
        "",
        f"// Auto-generated by tools/generator/data_class_generator.py — do not edit.",
        "",
        '#include <godot_cpp/classes/ref_counted.hpp>',
        '#include <godot_cpp/variant/dictionary.hpp>',
        '#include <godot_cpp/variant/packed_int32_array.hpp>',
        '#include <godot_cpp/variant/packed_float32_array.hpp>',
        "",
        '#include "../../misc/type_conversions.hpp"',
        "",
    ]

    # Forward declarations for nested structs
    nested_includes = set()
    for field, cls in convertible_fields:
        if cls == FieldClassification.NESTED_STRUCT:
            nested_includes.add(field.type)

    # Include nested data class headers
    for nested_type in sorted(nested_includes):
        nested_cls = to_godot_class_name(nested_type)
        nested_file = to_snake_case(nested_type)
        if nested_type.startswith("b3"):
            nested_file = nested_file[2:]  # strip b3 prefix
        lines.append(f'#include "box3d_{nested_file}.gen.hpp"')

    lines.append("")
    lines.append("using namespace godot;")
    lines.append("")

    T = "\t"
    # Class declaration
    lines.append(f"class {cls_name} : public godot::RefCounted {{")
    lines.append(f"{T}GDCLASS({cls_name}, RefCounted)")
    lines.append("")
    lines.append("public:")

    # Constructor + view setup for child structs (used as nested in parents)
    if is_child:
        lines.append(f"{T}{cls_name}();")
        lines.append(f"{T}~{cls_name}();")
        lines.append(
            f"{T}void set_as_view({struct.name}* p_data, RefCounted* p_parent);"
        )

    # Getter/setter declarations
    for field, cls in convertible_fields:
        godot_type = _resolve_field_type(field, cls, type_map)["cpp"]
        prop_name = to_snake_case(field.name)

        lines.append(f"{T}{godot_type} get_{prop_name}() const;")
        lines.append(f"{T}void set_{prop_name}({godot_type} p_value);")

    # to_b3 / from_b3 / ptr / copy
    lines.append(f"{T}{struct.name} to_b3() const;")
    lines.append(f"{T}void from_b3(const {struct.name}& p_data);")
    lines.append(f"{T}{struct.name}* ptr();")
    lines.append(f"{T}const {struct.name}* ptr() const;")
    lines.append(f"{T}Ref<{cls_name}> copy() const;")
    lines.append("")

    lines.append(f"{T}static void _bind_methods();")
    lines.append("")
    lines.append("private:")

    # Single embedded b3 struct member
    lines.append(f"{T}{struct.name} b3_;")

    # View infrastructure for child structs
    if is_child:
        lines.append(f"{T}mutable {struct.name}* _data_ptr;")
        lines.append(f"{T}Ref<RefCounted> _parent_ref;")

    lines.append("};")

    return "\n".join(lines) + "\n", warnings


def generate_implementation(struct: Struct, type_map: dict, all_struct_names: set,
                            skip_structs: set, snake: str = "") -> str:
    """Generate implementation file for a data class."""
    cls_name = to_godot_class_name(struct.name)
    T = "\t"

    convertible_fields = collect_convertible_fields(struct, type_map, all_struct_names, skip_structs)
    if not convertible_fields:
        return ""

    is_child = _is_child_struct(struct, type_map, all_struct_names, skip_structs)

    lines = [
        f'#include "box3d_{snake}.gen.hpp"',
        f'#include "data_class_helpers.gen.hpp"',
        '',
        "using namespace godot;",
        "",
    ]

    # --- Constructor + destructor + set_as_view for child structs ---
    if is_child:
        lines.append(f"{cls_name}::{cls_name}() : _data_ptr(&b3_) {{")
        lines.append("}")
        lines.append("")
        lines.append(f"{cls_name}::~{cls_name}() {{")
        lines.append("}")
        lines.append("")
        lines.append(f"void {cls_name}::set_as_view({struct.name}* p_data, RefCounted* p_parent) {{")
        lines.append(f"{T}_data_ptr = p_data;")
        lines.append(f"{T}_parent_ref = Ref<RefCounted>(p_parent);")
        lines.append("}")
        lines.append("")

    # --- Getters ---
    for field, cls in convertible_fields:
        prop_name = to_snake_case(field.name)

        if cls == FieldClassification.ARRAY:
            size = field.array_size
            base_type = field.type
            packed = "PackedFloat32Array" if base_type == "float" else "PackedInt32Array"
            lines.append(f"{packed} {cls_name}::get_{prop_name}() const {{")
            lines.append(f"{T}return _make_packed_array(_data_ptr->{field.name}, {packed}(), (size_t){size});")
            lines.append("}")
            lines.append("")
        elif cls == FieldClassification.NESTED_STRUCT:
            nested_cls = to_godot_class_name(field.type)
            godot_type = _resolve_field_type(field, cls, type_map)["cpp"]
            lines.append(f"{godot_type} {cls_name}::get_{prop_name}() const {{")
            lines.append(f"{T}Ref<{nested_cls}> ref;")
            lines.append(f"{T}ref.instantiate();")
            lines.append(
                f"{T}ref->set_as_view("
                f"const_cast<{field.type}*>(&_data_ptr->{field.name}),"
                f" const_cast<{cls_name}*>(this));"
            )
            lines.append(f"{T}return ref;")
            lines.append("}")
            lines.append("")
        else:
            field_access = f"_data_ptr->{field.name}"
            conv = convert_to_godot(field_access, field.type, type_map)
            lines.append(f"{_resolve_field_type(field, cls, type_map)['cpp']} {cls_name}::get_{prop_name}() const {{")
            lines.append(f"{T}return {conv};")
            lines.append("}")
            lines.append("")

    # --- Setters ---
    for field, cls in convertible_fields:
        prop_name = to_snake_case(field.name)
        godot_type = _resolve_field_type(field, cls, type_map)["cpp"]
        param = f"p_{prop_name}"

        if cls == FieldClassification.ARRAY:
            size = field.array_size
            base_type = field.type
            packed = "PackedFloat32Array" if base_type == "float" else "PackedInt32Array"
            lines.append(f"void {cls_name}::set_{prop_name}({packed} {param}) {{")
            lines.append(f"{T}_unpack_array({param}, _data_ptr->{field.name}, {size});")
            lines.append("}")
            lines.append("")
        elif cls == FieldClassification.NESTED_STRUCT:
            nested_cls = to_godot_class_name(field.type)
            lines.append(f"void {cls_name}::set_{prop_name}({godot_type} {param}) {{")
            lines.append(f"{T}if ({param}.is_valid()) {{")
            lines.append(f"{T}{T}_data_ptr->{field.name} = {param}->to_b3();")
            lines.append(f"{T}}}")
            lines.append("}")
            lines.append("")
        else:
            conv = convert_to_b3(param, field.type, type_map)
            lines.append(f"void {cls_name}::set_{prop_name}({godot_type} {param}) {{")
            lines.append(f"{T}_data_ptr->{field.name} = {conv};")
            lines.append("}")
            lines.append("")

    # --- to_b3() ---
    lines.append(f"{struct.name} {cls_name}::to_b3() const {{")
    lines.append(f"{T}return *_data_ptr;")
    lines.append("}")
    lines.append("")

    # --- from_b3() ---
    lines.append(f"void {cls_name}::from_b3(const {struct.name}& p_data) {{")
    lines.append(f"{T}*_data_ptr = p_data;")
    lines.append("}")
    lines.append("")

    # --- ptr() ---
    lines.append(f"{struct.name}* {cls_name}::ptr() {{")
    lines.append(f"{T}return _data_ptr;")
    lines.append("}")
    lines.append("")

    lines.append(f"const {struct.name}* {cls_name}::ptr() const {{")
    lines.append(f"{T}return _data_ptr;")
    lines.append("}")
    lines.append("")

    # --- copy() ---
    lines.append(f"Ref<{cls_name}> {cls_name}::copy() const {{")
    lines.append(f"{T}Ref<{cls_name}> c;")
    lines.append(f"{T}c.instantiate();")
    lines.append(f"{T}c->from_b3(to_b3());")
    lines.append(f"{T}return c;")
    lines.append("}")
    lines.append("")

    # --- _bind_methods() ---
    lines.append(f"void {cls_name}::_bind_methods() {{")

    # Bind copy method
    lines.append(f'{T}ClassDB::bind_method(D_METHOD("copy"), &{cls_name}::copy);')

    # Bind methods first (required before ADD_PROPERTY can reference them)
    for field, cls in convertible_fields:
        prop_name = to_snake_case(field.name)
        lines.append(
            f'{T}ClassDB::bind_method(D_METHOD("get_{prop_name}"), '
            f'&{cls_name}::get_{prop_name});'
        )
        lines.append(
            f'{T}ClassDB::bind_method(D_METHOD("set_{prop_name}", "value"), '
            f'&{cls_name}::set_{prop_name});'
        )

    lines.append("")

    # Add properties
    for field, cls in convertible_fields:
        prop_name = to_snake_case(field.name)
        getter = f"get_{prop_name}"
        setter = f"set_{prop_name}"
        variant_type = _resolve_field_type(field, cls, type_map)["variant"]

        # For Ref<T> types, we need the class name string
        # godot-cpp ADD_PROPERTY signature: (property_info, setter, getter)
        if cls == FieldClassification.NESTED_STRUCT:
            nested_cls = to_godot_class_name(field.type)
            lines.append(
                f'{T}ADD_PROPERTY(PropertyInfo(Variant::OBJECT, "{prop_name}", PROPERTY_HINT_NONE, '
                f'"{nested_cls}"), "{setter}", "{getter}");'
            )
        else:
            lines.append(
                f'{T}ADD_PROPERTY(PropertyInfo({variant_type}, "{prop_name}"), '
                f'"{setter}", "{getter}");'
            )

    lines.append("}")
    lines.append("")

    return "\n".join(lines) + "\n"


def _blob_field_type(field, cls, type_map: dict) -> str:
    """C++ type for a blob class field accessor."""
    if cls == FieldClassification.ARRAY:
        base = field.type
        return "PackedFloat32Array" if base == "float" else "PackedInt32Array"
    if cls == FieldClassification.ENUM:
        return field.type
    return to_godot_type(field.type, type_map, qualified=False)


def generate_blob_header(struct: Struct, type_map: dict, all_struct_names: set,
                         blobs: set, data: dict) -> str:
    """Generate header for a heap-blob data class (owning RefCounted).

    Unlike embedded data classes, a blob cannot be copied by value, so there is
    no ``to_b3``/``from_b3`` and no embedded ``b3_`` member. Ownership is held
    by ``_data_ptr`` + ``_owns`` and released via the destroy function in the
    destructor. ``take_ownership`` is an internal bridge used by generated
    Box3DAPI stubs and is intentionally NOT bound to ClassDB.
    """
    T = "\t"
    cls_name = to_godot_class_name(struct.name)
    fields = collect_convertible_fields(struct, type_map, all_struct_names, blobs)

    lines = [
        "#pragma once",
        "",
        "// Auto-generated by tools/generator/data_class_generator.py — do not edit.",
        "",
        '#include <godot_cpp/classes/ref_counted.hpp>',
        '#include <godot_cpp/variant/dictionary.hpp>',
        '#include <godot_cpp/variant/packed_int32_array.hpp>',
        '#include <godot_cpp/variant/packed_float32_array.hpp>',
        "",
        '#include "../../misc/type_conversions.hpp"',
        "",
        "using namespace godot;",
        "",
        f"class {cls_name} : public godot::RefCounted {{",
        f"{T}GDCLASS({cls_name}, RefCounted)",
        "",
        "public:",
        f"{T}{cls_name}();",
        f"{T}~{cls_name}();",
        f"{T}void take_ownership({struct.name}* p_data);",
        f"{T}void destroy();",
        f"{T}{struct.name}* ptr();",
        f"{T}const {struct.name}* ptr() const;",
    ]

    for field, cls in fields:
        cpp = _blob_field_type(field, cls, type_map)
        prop_name = to_snake_case(field.name)
        lines.append(f"{T}{cpp} get_{prop_name}() const;")
        lines.append(f"{T}void set_{prop_name}({cpp} p_value);")

    if infer_clone_fn(struct.name, data):
        lines.append(f"{T}Ref<{cls_name}> copy() const;")

    lines.append(f"{T}static void _bind_methods();")
    lines.append("")
    lines.append("private:")
    lines.append(f"{T}{struct.name}* _data_ptr;")
    lines.append(f"{T}bool _owns;")
    lines.append("};")

    return "\n".join(lines) + "\n"


def generate_blob_implementation(struct: Struct, type_map: dict, all_struct_names: set,
                                blobs: set, snake: str, data: dict) -> str:
    """Generate implementation for a heap-blob data class."""
    T = "\t"
    cls_name = to_godot_class_name(struct.name)
    destroy_fn = infer_destroy_fn(struct.name, data)
    clone_fn = infer_clone_fn(struct.name, data)
    fields = collect_convertible_fields(struct, type_map, all_struct_names, blobs)

    lines = [
        f'#include "box3d_{snake}.gen.hpp"',
        f'#include "data_class_helpers.gen.hpp"',
        "",
        "using namespace godot;",
        "",
        f"{cls_name}::{cls_name}() : _data_ptr(nullptr), _owns(false) {{",
        "}",
        "",
        f"{cls_name}::~{cls_name}() {{",
    ]
    if destroy_fn:
        lines.append(f"{T}if (_owns && _data_ptr) {{ {destroy_fn}(_data_ptr); }}")
    lines.append("}")
    lines.append("")
    lines.append(f"void {cls_name}::take_ownership({struct.name}* p_data) {{")
    lines.append(f"{T}_data_ptr = p_data;")
    lines.append(f"{T}_owns = true;")
    lines.append("}")
    lines.append("")
    if destroy_fn:
        lines.append(f"void {cls_name}::destroy() {{")
        lines.append(f"{T}if (_owns && _data_ptr) {{ {destroy_fn}(_data_ptr); }}")
        lines.append(f"{T}_owns = false;")
        lines.append(f"{T}_data_ptr = nullptr;")
        lines.append("}")
        lines.append("")
    lines.append(f"{struct.name}* {cls_name}::ptr() {{")
    lines.append(f"{T}return _data_ptr;")
    lines.append("}")
    lines.append("")
    lines.append(f"const {struct.name}* {cls_name}::ptr() const {{")
    lines.append(f"{T}return _data_ptr;")
    lines.append("}")
    lines.append("")

    for field, cls in fields:
        prop_name = to_snake_case(field.name)
        param = f"p_{prop_name}"

        if cls == FieldClassification.ARRAY:
            size = field.array_size
            base = field.type
            packed = "PackedFloat32Array" if base == "float" else "PackedInt32Array"
            lines.append(f"{packed} {cls_name}::get_{prop_name}() const {{")
            lines.append(f"{T}return _make_packed_array(_data_ptr->{field.name}, {packed}(), (size_t){size});")
            lines.append("}")
            lines.append("")
            lines.append(f"void {cls_name}::set_{prop_name}({packed} {param}) {{")
            lines.append(f"{T}_unpack_array({param}, _data_ptr->{field.name}, {size});")
            lines.append("}")
            lines.append("")
        else:
            cpp = _blob_field_type(field, cls, type_map)
            conv = convert_to_godot(f"_data_ptr->{field.name}", field.type, type_map)
            lines.append(f"{cpp} {cls_name}::get_{prop_name}() const {{")
            lines.append(f"{T}return {conv};")
            lines.append("}")
            lines.append("")
            cb = convert_to_b3(param, field.type, type_map)
            lines.append(f"void {cls_name}::set_{prop_name}({cpp} {param}) {{")
            lines.append(f"{T}_data_ptr->{field.name} = {cb};")
            lines.append("}")
            lines.append("")

    if clone_fn:
        lines.append(f"Ref<{cls_name}> {cls_name}::copy() const {{")
        lines.append(f"{T}Ref<{cls_name}> c;")
        lines.append(f"{T}c.instantiate();")
        lines.append(f"{T}c->take_ownership({clone_fn}(_data_ptr));")
        lines.append(f"{T}return c;")
        lines.append("}")
        lines.append("")

    lines.append(f"void {cls_name}::_bind_methods() {{")
    if clone_fn:
        lines.append(f'{T}ClassDB::bind_method(D_METHOD("copy"), &{cls_name}::copy);')
    lines.append(f'{T}ClassDB::bind_method(D_METHOD("destroy"), &{cls_name}::destroy);')

    for field, cls in fields:
        prop_name = to_snake_case(field.name)
        lines.append(
            f'{T}ClassDB::bind_method(D_METHOD("get_{prop_name}"), '
            f'&{cls_name}::get_{prop_name});'
        )
        lines.append(
            f'{T}ClassDB::bind_method(D_METHOD("set_{prop_name}", "value"), '
            f'&{cls_name}::set_{prop_name});'
        )
    lines.append("")

    for field, cls in fields:
        prop_name = to_snake_case(field.name)
        variant_type = _resolve_field_type(field, cls, type_map)["variant"]
        lines.append(
            f'{T}ADD_PROPERTY(PropertyInfo({variant_type}, "{prop_name}"), '
            f'"set_{prop_name}", "get_{prop_name}");'
        )

    lines.append("}")
    lines.append("")
    return "\n".join(lines) + "\n"


def generate_data_classes(root: str) -> tuple[int, list[str]]:
    """Generate all data class files.

    Returns (class_count, warnings).
    """
    type_map = load_type_map(root)
    data = parse_headers(root)

    skip_structs = set(type_map.get("skip_structs", []))
    math_types = set(type_map.get("math_types", {}).keys())
    id_types = set(type_map.get("id_types", {}).keys())
    skip_enum_names = set(type_map.get("skip_enums", []))
    type_map["enums"], type_map["enum_constants"] = build_enum_info(data["enums"], skip_enum_names)

    # Blob structs inferred by parser (byteCount + Offset fields).
    # These get separate RefCounted wrappers instead of embedded mode.
    blobs = set(blob_structs(data))
    eff_skip = skip_structs | blobs

    # Filter: all structs except skip_structs, blobs, math_types, id_types, enums
    candidates = [
        s
        for s in data["structs"]
        if s.name not in eff_skip
        and s.name not in math_types
        and s.name not in id_types
        and s.name not in type_map["enums"]
    ]

    all_struct_names = {s.name for s in data["structs"]}

    # Sort by dependency
    deps = compute_struct_dependencies(candidates)
    sorted_structs = topological_sort(candidates, deps)

    out_dir = Path(root) / "src" / "bindings" / "data_classes"
    # Sweep the whole directory so output always matches the current generator.
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    all_warnings = []
    generated = 0
    generated_files = []

    for struct in sorted_structs:
        snake = data_class_filename(struct.name)

        header_content, warns = generate_header(
            struct, type_map, all_struct_names, eff_skip
        )
        all_warnings.extend(warns)

        if not header_content:
            continue

        impl_content = generate_implementation(
            struct, type_map, all_struct_names, eff_skip, snake
        )

        # Write header
        header_path = out_dir / f"box3d_{snake}.gen.hpp"
        header_path.write_text(header_content)

        # Write implementation
        impl_path = out_dir / f"box3d_{snake}.gen.cpp"
        impl_path.write_text(impl_content)

        generated_files.append(snake)
        generated += 1

    # Generate blob classes (owning RefCounted wrappers for heap blobs)
    for struct in sorted(data["structs"], key=lambda s: s.name):
        if struct.name not in blobs:
            continue

        snake = data_class_filename(struct.name)
        header_content = generate_blob_header(
            struct, type_map, all_struct_names, eff_skip, data
        )
        impl_content = generate_blob_implementation(
            struct, type_map, all_struct_names, eff_skip, snake, data
        )

        out_dir.joinpath(f"box3d_{snake}.gen.hpp").write_text(header_content)
        out_dir.joinpath(f"box3d_{snake}.gen.cpp").write_text(impl_content)

        generated_files.append(snake)
        generated += 1

    # Generate helpers header
    helpers_path = out_dir / "data_class_helpers.gen.hpp"
    helpers_lines = [
        "#pragma once",
        "",
        "// Auto-generated shared helper functions for Box3D data class conversions.",
        "",
        "#include <godot_cpp/classes/ref_counted.hpp>",
        "#include <godot_cpp/core/class_db.hpp>",
        "#include <godot_cpp/variant/packed_int32_array.hpp>",
        "#include <godot_cpp/variant/packed_float32_array.hpp>",
        "",
        "using namespace godot;",
        "",
    ]

    # VARIANT_ENUM_CAST for each enum type (must be in helpers so all .cpp files see them)
    for enum_name in type_map.get("enums", []):
        helpers_lines.append(f"VARIANT_ENUM_CAST({enum_name});")

    helpers_lines.append("")
    helpers_lines.append(generate_helper_functions())
    helpers_lines.append("")

    helpers_path.write_text("\n".join(helpers_lines) + "\n")

    # Generate umbrella header
    umbrella = [
        "#pragma once",
        "",
        "// Auto-generated umbrella header for all Box3D data classes.",
        "// Includes all generated data class headers and shared helpers.",
        "",
        "#include <godot_cpp/classes/ref_counted.hpp>",
        "#include <godot_cpp/variant/packed_int32_array.hpp>",
        "#include <godot_cpp/variant/packed_float32_array.hpp>",
        "",
        '#include "../../misc/type_conversions.hpp"',
        '',
        '#include "data_class_helpers.gen.hpp"',
        "",
    ]

    for snake in sorted(generated_files):
        umbrella.append(f'#include "box3d_{snake}.gen.hpp"')

    umbrella.append("")
    umbrella.append("using namespace godot;")

    # Add registration function declaration
    umbrella.append("")
    umbrella.append("// Register all data classes with ClassDB")
    umbrella.append("void register_data_classes();")

    umbrella_path = out_dir / "data_classes.gen.hpp"
    umbrella_path.write_text("\n".join(umbrella) + "\n")

    # Generate registration implementation
    T = "\t"
    reg_lines = [
        "#include \"data_classes.gen.hpp\"",
        "",
        "void register_data_classes() {",
    ]
    for struct in sorted_structs:
        cls_name = to_godot_class_name(struct.name)
        reg_lines.append(f'{T}ClassDB::register_class<{cls_name}>();')
    for struct in sorted(data["structs"], key=lambda s: s.name):
        if struct.name not in blobs:
            continue
        cls_name = to_godot_class_name(struct.name)
        reg_lines.append(f'{T}ClassDB::register_class<{cls_name}>();')

    reg_lines.append("}")
    reg_lines.append("")

    reg_path = out_dir / "data_classes_register.gen.cpp"
    reg_path.write_text("\n".join(reg_lines) + "\n")

    return generated, all_warnings


def main():
    import argparse

    parser = argparse.ArgumentParser(description="Generate Box3D data classes")
    parser.add_argument("root", nargs="?", default=".", help="Project root directory")
    args = parser.parse_args()

    count, warnings = generate_data_classes(args.root)
    print(f"Generated {count} data classes in src/bindings/data_classes/")

    if warnings:
        print(f"\nWarnings ({len(warnings)}):")
        for w in warnings:
            print(w)


if __name__ == "__main__":
    main()
